//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sismuni.Dominio.Negocio.Recursos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GrupoTabla {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GrupoTabla() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sismuni.Dominio.Negocio.Recursos.GrupoTabla", typeof(GrupoTabla).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0006.
        /// </summary>
        public static string EstadoReciboProvisional {
            get {
                return ResourceManager.GetString("EstadoReciboProvisional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0010.
        /// </summary>
        public static string EstadoSolicitudPagoServicio {
            get {
                return ResourceManager.GetString("EstadoSolicitudPagoServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0005.
        /// </summary>
        public static string EstadosSolicitud {
            get {
                return ResourceManager.GetString("EstadosSolicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0004.
        /// </summary>
        public static string ModoEnvio {
            get {
                return ResourceManager.GetString("ModoEnvio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0007.
        /// </summary>
        public static string RangoHorarios {
            get {
                return ResourceManager.GetString("RangoHorarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0001.
        /// </summary>
        public static string TipoDocumento {
            get {
                return ResourceManager.GetString("TipoDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0002.
        /// </summary>
        public static string TipoExpediente {
            get {
                return ResourceManager.GetString("TipoExpediente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0003.
        /// </summary>
        public static string TipoInformacionMunicipal {
            get {
                return ResourceManager.GetString("TipoInformacionMunicipal", resourceCulture);
            }
        }
    }
}
