//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sismuni.Infraestructura.Data.UnidadDeTrabajo
{
    using Sismuni.Infraestructura.Data.Base;
    using Sismuni.Infraestructura.Data.Modelo;
    using System.Data.Entity;
    
    public interface IModeloUnidadDeTrabajo : IConsultaUnidadDeTrabajo
    {
        DbSet<Estado> Estado { get; set; }
        DbSet<UsuarioTrabajador> UsuarioTrabajador { get; set; }
        DbSet<Area> Area { get; set; }
        DbSet<Cargo> Cargo { get; set; }
        DbSet<GrupoTabla> GrupoTabla { get; set; }
        DbSet<Multitabla> Multitabla { get; set; }
        DbSet<Expediente> Expediente { get; set; }
        DbSet<SolicitudInformacionMunicipal> SolicitudInformacionMunicipal { get; set; }
        DbSet<CO_Area> CO_Area { get; set; }
        DbSet<CO_Cargo> CO_Cargo { get; set; }
        DbSet<CO_Ciudadano> CO_Ciudadano { get; set; }
        DbSet<CO_Documento> CO_Documento { get; set; }
        DbSet<CO_Empleado> CO_Empleado { get; set; }
        DbSet<CO_Expediente_Elim> CO_Expediente_Elim { get; set; }
        DbSet<CO_Perfil> CO_Perfil { get; set; }
        DbSet<CO_Rol> CO_Rol { get; set; }
        DbSet<CO_Tipo_Documento> CO_Tipo_Documento { get; set; }
        DbSet<CO_Tramite> CO_Tramite { get; set; }
        DbSet<CO_Ubigeo> CO_Ubigeo { get; set; }
        DbSet<CO_Usuario> CO_Usuario { get; set; }
        DbSet<LI_disponibilidadinspector> LI_disponibilidadinspector { get; set; }
        DbSet<LI_informeinspeccion> LI_informeinspeccion { get; set; }
        DbSet<LI_solicitudlicencia> LI_solicitudlicencia { get; set; }
        DbSet<NO_Expediente_Elim> NO_Expediente_Elim { get; set; }
        DbSet<NO_InformacionMunicipal> NO_InformacionMunicipal { get; set; }
        DbSet<NO_InformeMunicipal> NO_InformeMunicipal { get; set; }
        DbSet<NO_SolicitudInformacionArea> NO_SolicitudInformacionArea { get; set; }
        DbSet<NO_SolicitudInformacionMunicipal> NO_SolicitudInformacionMunicipal { get; set; }
        DbSet<NO_TipoExpediente_Elim> NO_TipoExpediente_Elim { get; set; }
        DbSet<PR_Categoria> PR_Categoria { get; set; }
        DbSet<PR_Figuracion> PR_Figuracion { get; set; }
        DbSet<PR_Genericas> PR_Genericas { get; set; }
        DbSet<PR_Gerencia> PR_Gerencia { get; set; }
        DbSet<PR_Jefatura> PR_Jefatura { get; set; }
        DbSet<PR_Presupuesto> PR_Presupuesto { get; set; }
        DbSet<PR_Solicitud> PR_Solicitud { get; set; }
        DbSet<PR_Version> PR_Version { get; set; }
        DbSet<PV_Acta_Confirmacion_Elim> PV_Acta_Confirmacion_Elim { get; set; }
        DbSet<PV_Acta_reunion> PV_Acta_reunion { get; set; }
        DbSet<PV_Asunto> PV_Asunto { get; set; }
        DbSet<PV_DetalleExpediente_Elim> PV_DetalleExpediente_Elim { get; set; }
        DbSet<PV_DetalleRequisito_Elim> PV_DetalleRequisito_Elim { get; set; }
        DbSet<PV_DocumentoAdjunto_Elim> PV_DocumentoAdjunto_Elim { get; set; }
        DbSet<PV_DocumentosRequerimientos_Elim> PV_DocumentosRequerimientos_Elim { get; set; }
        DbSet<PV_DocumentoValidado_Elim> PV_DocumentoValidado_Elim { get; set; }
        DbSet<PV_Estado_Elim> PV_Estado_Elim { get; set; }
        DbSet<PV_Informe_Gerencia_Elim> PV_Informe_Gerencia_Elim { get; set; }
        DbSet<PV_Informe_Sectorista_Elim> PV_Informe_Sectorista_Elim { get; set; }
        DbSet<PV_InformeInspeccion_Elim> PV_InformeInspeccion_Elim { get; set; }
        DbSet<PV_Iniciativa_Vecinal> PV_Iniciativa_Vecinal { get; set; }
        DbSet<PV_NivelOrganizacion_Elim> PV_NivelOrganizacion_Elim { get; set; }
        DbSet<PV_OrganizacionSocial_Elim> PV_OrganizacionSocial_Elim { get; set; }
        DbSet<PV_Participantes_Organizacion_Elim> PV_Participantes_Organizacion_Elim { get; set; }
        DbSet<PV_Reporte_Elim> PV_Reporte_Elim { get; set; }
        DbSet<PV_ReporteObs_Elim> PV_ReporteObs_Elim { get; set; }
        DbSet<PV_Requerimiento> PV_Requerimiento { get; set; }
        DbSet<PV_RequisitoOrganizacion_Elim> PV_RequisitoOrganizacion_Elim { get; set; }
        DbSet<PV_Reunion> PV_Reunion { get; set; }
        DbSet<PV_Sector> PV_Sector { get; set; }
        DbSet<PV_SubSector> PV_SubSector { get; set; }
        DbSet<PV_SubTipoOrganizacion_Elim> PV_SubTipoOrganizacion_Elim { get; set; }
        DbSet<PV_SubTipoRequisto_Elim> PV_SubTipoRequisto_Elim { get; set; }
        DbSet<PV_Tipo_Reporte_Elim> PV_Tipo_Reporte_Elim { get; set; }
        DbSet<PV_TipoOrganizacion_Elim> PV_TipoOrganizacion_Elim { get; set; }
        DbSet<PV_Vecino> PV_Vecino { get; set; }
        DbSet<TR_DetalleSolicitudTramite> TR_DetalleSolicitudTramite { get; set; }
        DbSet<TR_RequisitoTramite> TR_RequisitoTramite { get; set; }
        DbSet<TR_SolicitudTramite> TR_SolicitudTramite { get; set; }
        DbSet<TR_Tipo_Tramite> TR_Tipo_Tramite { get; set; }
        DbSet<LI_inspeccion> LI_inspeccion { get; set; }
    }
}
