//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sismuni.Infraestructura.Data.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CO_Expediente_Elim
    {
        public int ID_Expediente { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string Observacion { get; set; }
        public string Estado { get; set; }
        public int ID_OrganizacionSocial { get; set; }
        public int ID_Usuario { get; set; }
        public int ID_Ciudadano { get; set; }
    }
}
