//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sismuni.Infraestructura.Data.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CO_Empleado
    {
        public int ID_Empleado { get; set; }
        public string Nombres { get; set; }
        public string Apellido_Paterno { get; set; }
        public string Apellido_Materno { get; set; }
        public string Numero_Documento { get; set; }
        public Nullable<System.DateTime> Fecha_Ingreso { get; set; }
        public Nullable<System.DateTime> Fecha_Cese { get; set; }
        public Nullable<int> Estado { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
        public string ID_Tipo_Documento { get; set; }
        public Nullable<System.DateTime> Fecha_Nacimiento { get; set; }
        public string Direccion { get; set; }
        public string Celular { get; set; }
        public Nullable<int> ID_Area { get; set; }
        public Nullable<int> ID_Cargo { get; set; }
    }
}
