//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sismuni.Infraestructura.Data.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CO_Rol
    {
        public int ID_Rol { get; set; }
        public Nullable<int> ID_UsuarioRol { get; set; }
        public Nullable<int> ID_PerfilRol { get; set; }
        public Nullable<int> CodigoModuloRol { get; set; }
        public string DescripcionModuloRol { get; set; }
        public Nullable<int> EjecutarRol { get; set; }
        public Nullable<int> CosultarRol { get; set; }
        public Nullable<int> ModificaRol { get; set; }
        public Nullable<int> EstadoRol { get; set; }
    }
}
