//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sismuni.Infraestructura.Data.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CO_Tramite
    {
        public int ID_Tramite { get; set; }
        public string NroTramite { get; set; }
        public Nullable<System.DateTime> FechaEmision { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> IdSolicitudTramite { get; set; }
        public string Estado { get; set; }
    }
}
