//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sismuni.Infraestructura.Data.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expediente
    {
        public long NumeroExpediente { get; set; }
        public Nullable<System.DateTime> FechaExpediente { get; set; }
        public Nullable<long> NumeroSolicitud { get; set; }
        public string Tipo_Expediente { get; set; }
        public string Asunto { get; set; }
        public Nullable<int> Estado { get; set; }
    
        public virtual Multitabla Multitabla { get; set; }
        public virtual SolicitudInformacionMunicipal SolicitudInformacionMunicipal { get; set; }
    }
}
