//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sismuni.Infraestructura.Data.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrupoTabla
    {
        public GrupoTabla()
        {
            this.Multitabla = new HashSet<Multitabla>();
        }
    
        public string IdGrupo { get; set; }
        public string NombreGrupo { get; set; }
        public Nullable<int> Estado { get; set; }
    
        public virtual ICollection<Multitabla> Multitabla { get; set; }
    }
}
