//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sismuni.Infraestructura.Data.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UPC_MUNIEntities : DbContext
    {
        public UPC_MUNIEntities()
            : base("name=UPC_MUNIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Estado> Estado { get; set; }
        public DbSet<UsuarioTrabajador> UsuarioTrabajador { get; set; }
        public DbSet<Area> Area { get; set; }
        public DbSet<Cargo> Cargo { get; set; }
        public DbSet<GrupoTabla> GrupoTabla { get; set; }
        public DbSet<Multitabla> Multitabla { get; set; }
        public DbSet<Expediente> Expediente { get; set; }
        public DbSet<SolicitudInformacionMunicipal> SolicitudInformacionMunicipal { get; set; }
        public DbSet<CO_Area> CO_Area { get; set; }
        public DbSet<CO_Cargo> CO_Cargo { get; set; }
        public DbSet<CO_Ciudadano> CO_Ciudadano { get; set; }
        public DbSet<CO_Documento> CO_Documento { get; set; }
        public DbSet<CO_Empleado> CO_Empleado { get; set; }
        public DbSet<CO_Expediente_Elim> CO_Expediente_Elim { get; set; }
        public DbSet<CO_Perfil> CO_Perfil { get; set; }
        public DbSet<CO_Rol> CO_Rol { get; set; }
        public DbSet<CO_Tipo_Documento> CO_Tipo_Documento { get; set; }
        public DbSet<CO_Tramite> CO_Tramite { get; set; }
        public DbSet<CO_Ubigeo> CO_Ubigeo { get; set; }
        public DbSet<CO_Usuario> CO_Usuario { get; set; }
        public DbSet<LI_disponibilidadinspector> LI_disponibilidadinspector { get; set; }
        public DbSet<LI_informeinspeccion> LI_informeinspeccion { get; set; }
        public DbSet<LI_solicitudlicencia> LI_solicitudlicencia { get; set; }
        public DbSet<NO_Expediente_Elim> NO_Expediente_Elim { get; set; }
        public DbSet<NO_InformacionMunicipal> NO_InformacionMunicipal { get; set; }
        public DbSet<NO_InformeMunicipal> NO_InformeMunicipal { get; set; }
        public DbSet<NO_SolicitudInformacionArea> NO_SolicitudInformacionArea { get; set; }
        public DbSet<NO_SolicitudInformacionMunicipal> NO_SolicitudInformacionMunicipal { get; set; }
        public DbSet<NO_TipoExpediente_Elim> NO_TipoExpediente_Elim { get; set; }
        public DbSet<PR_Categoria> PR_Categoria { get; set; }
        public DbSet<PR_Figuracion> PR_Figuracion { get; set; }
        public DbSet<PR_Genericas> PR_Genericas { get; set; }
        public DbSet<PR_Gerencia> PR_Gerencia { get; set; }
        public DbSet<PR_Jefatura> PR_Jefatura { get; set; }
        public DbSet<PR_Presupuesto> PR_Presupuesto { get; set; }
        public DbSet<PR_Solicitud> PR_Solicitud { get; set; }
        public DbSet<PR_Version> PR_Version { get; set; }
        public DbSet<PV_Acta_Confirmacion_Elim> PV_Acta_Confirmacion_Elim { get; set; }
        public DbSet<PV_Acta_reunion> PV_Acta_reunion { get; set; }
        public DbSet<PV_Asunto> PV_Asunto { get; set; }
        public DbSet<PV_DetalleExpediente_Elim> PV_DetalleExpediente_Elim { get; set; }
        public DbSet<PV_DetalleRequisito_Elim> PV_DetalleRequisito_Elim { get; set; }
        public DbSet<PV_DocumentoAdjunto_Elim> PV_DocumentoAdjunto_Elim { get; set; }
        public DbSet<PV_DocumentosRequerimientos_Elim> PV_DocumentosRequerimientos_Elim { get; set; }
        public DbSet<PV_DocumentoValidado_Elim> PV_DocumentoValidado_Elim { get; set; }
        public DbSet<PV_Estado_Elim> PV_Estado_Elim { get; set; }
        public DbSet<PV_Informe_Gerencia_Elim> PV_Informe_Gerencia_Elim { get; set; }
        public DbSet<PV_Informe_Sectorista_Elim> PV_Informe_Sectorista_Elim { get; set; }
        public DbSet<PV_InformeInspeccion_Elim> PV_InformeInspeccion_Elim { get; set; }
        public DbSet<PV_Iniciativa_Vecinal> PV_Iniciativa_Vecinal { get; set; }
        public DbSet<PV_NivelOrganizacion_Elim> PV_NivelOrganizacion_Elim { get; set; }
        public DbSet<PV_OrganizacionSocial_Elim> PV_OrganizacionSocial_Elim { get; set; }
        public DbSet<PV_Participantes_Organizacion_Elim> PV_Participantes_Organizacion_Elim { get; set; }
        public DbSet<PV_Reporte_Elim> PV_Reporte_Elim { get; set; }
        public DbSet<PV_ReporteObs_Elim> PV_ReporteObs_Elim { get; set; }
        public DbSet<PV_Requerimiento> PV_Requerimiento { get; set; }
        public DbSet<PV_RequisitoOrganizacion_Elim> PV_RequisitoOrganizacion_Elim { get; set; }
        public DbSet<PV_Reunion> PV_Reunion { get; set; }
        public DbSet<PV_Sector> PV_Sector { get; set; }
        public DbSet<PV_SubSector> PV_SubSector { get; set; }
        public DbSet<PV_SubTipoOrganizacion_Elim> PV_SubTipoOrganizacion_Elim { get; set; }
        public DbSet<PV_SubTipoRequisto_Elim> PV_SubTipoRequisto_Elim { get; set; }
        public DbSet<PV_Tipo_Reporte_Elim> PV_Tipo_Reporte_Elim { get; set; }
        public DbSet<PV_TipoOrganizacion_Elim> PV_TipoOrganizacion_Elim { get; set; }
        public DbSet<PV_Vecino> PV_Vecino { get; set; }
        public DbSet<TR_DetalleSolicitudTramite> TR_DetalleSolicitudTramite { get; set; }
        public DbSet<TR_RequisitoTramite> TR_RequisitoTramite { get; set; }
        public DbSet<TR_SolicitudTramite> TR_SolicitudTramite { get; set; }
        public DbSet<TR_Tipo_Tramite> TR_Tipo_Tramite { get; set; }
        public DbSet<LI_inspeccion> LI_inspeccion { get; set; }
    }
}
