//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sismuni.Infraestructura.Data.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class NO_Expediente_Elim
    {
        public NO_Expediente_Elim()
        {
            this.NO_SolicitudInformacionArea = new HashSet<NO_SolicitudInformacionArea>();
        }
    
        public int idNumeroExpediente { get; set; }
        public int idTipoExpediente { get; set; }
        public int idNumeroSolicitud { get; set; }
        public Nullable<System.DateTime> FechaExpediente { get; set; }
        public string Asunto { get; set; }
        public Nullable<int> Estado { get; set; }
    
        public virtual NO_SolicitudInformacionMunicipal NO_SolicitudInformacionMunicipal { get; set; }
        public virtual NO_TipoExpediente_Elim NO_TipoExpediente_Elim { get; set; }
        public virtual ICollection<NO_SolicitudInformacionArea> NO_SolicitudInformacionArea { get; set; }
    }
}
