//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sismuni.Infraestructura.Data.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class NO_InformacionMunicipal
    {
        public int NumeroInformacionMunicipal { get; set; }
        public int idNUmeroSolicitud { get; set; }
        public string CodigoDocumento { get; set; }
        public string Titulo { get; set; }
        public string VersionIM { get; set; }
        public string SubTipoInformacion { get; set; }
        public string CategoriaInformación { get; set; }
        public Nullable<System.DateTime> Fechaemision { get; set; }
        public Nullable<System.DateTime> FechaVigencia { get; set; }
        public string TipoInformacion { get; set; }
    
        public virtual NO_SolicitudInformacionMunicipal NO_SolicitudInformacionMunicipal { get; set; }
    }
}
