//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sismuni.Infraestructura.Data.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class NO_InformeMunicipal
    {
        public int idNumeroInforme { get; set; }
        public int idNumeroSolicitud { get; set; }
        public Nullable<System.DateTime> FechaInforme { get; set; }
        public string NombresSolicitante { get; set; }
        public string ApellidoSoliciante { get; set; }
        public string Descripcion { get; set; }
        public string Observacion { get; set; }
        public string TipoInforme { get; set; }
    
        public virtual NO_SolicitudInformacionMunicipal NO_SolicitudInformacionMunicipal { get; set; }
    }
}
