//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sismuni.Infraestructura.Data.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class NO_TipoExpediente_Elim
    {
        public NO_TipoExpediente_Elim()
        {
            this.NO_Expediente_Elim = new HashSet<NO_Expediente_Elim>();
        }
    
        public int idTipoExpediente { get; set; }
        public string DescripcionTipoExpediente { get; set; }
    
        public virtual ICollection<NO_Expediente_Elim> NO_Expediente_Elim { get; set; }
    }
}
