//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sismuni.Infraestructura.Data.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PR_Categoria
    {
        public int idCategoria { get; set; }
        public int idGenericasCategoria { get; set; }
        public string DescripcionCategoria { get; set; }
        public string TipoCategoria { get; set; }
    }
}
