//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sismuni.Infraestructura.Data.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PR_Gerencia
    {
        public int idGerencia { get; set; }
        public string DescripcionGerencia { get; set; }
        public Nullable<int> EstadoGerencia { get; set; }
    }
}
