//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sismuni.Infraestructura.Data.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PR_Presupuesto
    {
        public int idPresupuesto { get; set; }
        public int idVersion { get; set; }
        public int idCategoriaPresupuesto { get; set; }
        public int idGenericaPresupuesto { get; set; }
        public int idAreaPresupuesto { get; set; }
        public int idSolicitudPresupuesto { get; set; }
        public Nullable<System.DateTime> FechaPresupuesto { get; set; }
        public string AnnoPresupuesto { get; set; }
        public string PeriodoPresupuesto { get; set; }
        public string TipoCuentaPresupuesto { get; set; }
        public Nullable<decimal> TotalPresupuesto { get; set; }
    }
}
