//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sismuni.Infraestructura.Data.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PR_Solicitud
    {
        public int idSolicitud { get; set; }
        public Nullable<int> NumeroSolicitud { get; set; }
        public Nullable<System.DateTime> FechaSolicitud { get; set; }
        public Nullable<int> idCategoriaSolicitud { get; set; }
        public Nullable<int> idGenericasSolicitud { get; set; }
        public string PeriodoSolicitud { get; set; }
        public Nullable<decimal> TotalSolicitud { get; set; }
        public Nullable<int> EstadoSolicitud { get; set; }
    }
}
