//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sismuni.Infraestructura.Data.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PV_Acta_reunion
    {
        public int ID_Acta_Reunion { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public int ID_Iniciativa_Vecinal { get; set; }
    }
}
