//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sismuni.Infraestructura.Data.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PV_DetalleExpediente_Elim
    {
        public System.DateTime FechaValidacion { get; set; }
        public bool CumpleRequisito { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string RutaArchivo { get; set; }
        public int ID_Expediente { get; set; }
        public int ID_RequisitoOrganizacion { get; set; }
    }
}
