//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sismuni.Infraestructura.Data.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PV_DocumentoValidado_Elim
    {
        public System.DateTime FechaValidacion { get; set; }
        public bool CumpleRequisito { get; set; }
        public int PV_RequisitoOrganizacion_ID { get; set; }
        public int PV_Expediente_ID { get; set; }
        public int PV_DetalleExpediente_PV_RequisitoOrganizacion_ID { get; set; }
    }
}
