//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sismuni.Infraestructura.Data.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PV_DocumentoAdjunto_Elim
    {
        public string NombreDoc { get; set; }
        public string RutaDoc { get; set; }
        public int PV_Area_ID { get; set; }
        public int PV_Documentos_ID { get; set; }
        public int PV_DocumentosRequerimientos_PV_Documentos_ID { get; set; }
    }
}
