//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sismuni.Infraestructura.Data.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PV_InformeInspeccion_Elim
    {
        public int PV_InformeInspeccion_ID { get; set; }
        public System.DateTime FechaInspeccion { get; set; }
        public string Observacion { get; set; }
        public bool ZonaIntangible { get; set; }
        public bool AprobarInforme { get; set; }
    }
}
