//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sismuni.Infraestructura.Data.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PV_Iniciativa_Vecinal
    {
        public int ID_Iniciativa_Vecinal { get; set; }
        public System.DateTime Fecha_Registro { get; set; }
        public string Hora { get; set; }
        public string Descripcion_Corta { get; set; }
        public string Detalle_Iniciativa { get; set; }
        public System.DateTime Fecha_Notificacion { get; set; }
        public int ID_Sector { get; set; }
        public int ID_Ciudadano { get; set; }
        public Nullable<int> ID_SubSector { get; set; }
    }
}
