//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sismuni.Infraestructura.Data.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PV_NivelOrganizacion_Elim
    {
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public bool FlDistrito { get; set; }
        public int PV_NivelOrganizacion_ID { get; set; }
    }
}
