//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sismuni.Infraestructura.Data.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PV_OrganizacionSocial_Elim
    {
        public System.DateTime Fecha_inscripcion { get; set; }
        public string CodigoRUOS { get; set; }
        public System.DateTime FechaFundacion { get; set; }
        public string DescripcionObjetivo { get; set; }
        public string Direccion { get; set; }
        public string NombreOrganizacion { get; set; }
        public int PV_OrganizacionSocial_ID { get; set; }
        public int PV_Sector_ID { get; set; }
        public int PV_TipoOrganizacion_ID { get; set; }
        public Nullable<int> PV_NivelOrganizacion_ID { get; set; }
        public int PV_InformeInspeccion_ID { get; set; }
    }
}
