//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sismuni.Infraestructura.Data.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PV_Reunion
    {
        public int ID_Reunion { get; set; }
        public string Nombre_Reunion { get; set; }
        public System.DateTime Fecha_Reunion { get; set; }
        public string Hora_Primera_Cita { get; set; }
        public string Hora_Segunda_Cita { get; set; }
        public string Otros_Acuerdos { get; set; }
        public int ID_Iniciativa_Vecinal { get; set; }
    }
}
