//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sismuni.Infraestructura.Data.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PV_Reporte_Elim
    {
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaIncio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public string Titulo { get; set; }
        public string Contexto { get; set; }
        public int PV_Reporte_ID { get; set; }
        public int PV_Requerimiento_ID { get; set; }
        public Nullable<int> PV_Usuario_ID { get; set; }
        public int PV_Tipo_Reporte_ID { get; set; }
        public int PV_Trabajador_ID { get; set; }
    }
}
