//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sismuni.Infraestructura.Data.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PV_Vecino
    {
        public string Direccion_Predio { get; set; }
        public string Delegado_Vecinal { get; set; }
        public int ID_Ciudadano { get; set; }
    }
}
