//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sismuni.Infraestructura.Data.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudInformacionMunicipal
    {
        public SolicitudInformacionMunicipal()
        {
            this.Expediente = new HashSet<Expediente>();
        }
    
        public long NumeroSolicitud { get; set; }
        public Nullable<System.DateTime> FechaSolicitud { get; set; }
        public string NombresSolicitante { get; set; }
        public string ApellidoPaternoSolicitante { get; set; }
        public string ApellidoMaternoSolicitante { get; set; }
        public string TipoDocumento { get; set; }
        public string NumeroDocumento { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public string Email { get; set; }
        public string Modo_Envio { get; set; }
        public Nullable<int> IdUsuarioTrabajador { get; set; }
        public string Tipo_Informacion { get; set; }
        public string Motivo_Solicitud { get; set; }
        public string Observaciones { get; set; }
        public string Estado { get; set; }
    
        public virtual UsuarioTrabajador UsuarioTrabajador { get; set; }
        public virtual Multitabla Multitabla { get; set; }
        public virtual Multitabla Multitabla1 { get; set; }
        public virtual ICollection<Expediente> Expediente { get; set; }
        public virtual Multitabla Multitabla11 { get; set; }
    }
}
