//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sismuni.Infraestructura.Data.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_DetalleSolicitudTramite
    {
        public int IdDetalleSolicitudTramite { get; set; }
        public int IdSolicitudTramite { get; set; }
        public string Informacion { get; set; }
        public string NombreAdjunto { get; set; }
        public string Observaciones { get; set; }
        public string RutaAdjunto { get; set; }
    }
}
