//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sismuni.Infraestructura.Data.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_SolicitudTramite
    {
        public int IdSolicitudTramite { get; set; }
        public string NroSolicitud { get; set; }
        public string CodigoOperacion { get; set; }
        public string FechaSolicitud { get; set; }
        public string Observaciones { get; set; }
        public string Estado { get; set; }
        public int ID_Ciudadano { get; set; }
        public int ID_Tipo_Tramite { get; set; }
    }
}
