//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sismuni.Infraestructura.Data.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_Tipo_Tramite
    {
        public int ID_Tipo_Tramite { get; set; }
        public string Descripcion { get; set; }
        public string Vigencia { get; set; }
        public string Estado { get; set; }
    }
}
