//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sismuni.Presentacion.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ContentType {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContentType() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sismuni.Presentacion.Web.Resources.ContentType", typeof(ContentType).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/bmp.
        /// </summary>
        internal static string CT_Bmp {
            get {
                return ResourceManager.GetString("CT_Bmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text/csv.
        /// </summary>
        internal static string CT_Csv {
            get {
                return ResourceManager.GetString("CT_Csv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/octet-stream.
        /// </summary>
        internal static string CT_Desconocido {
            get {
                return ResourceManager.GetString("CT_Desconocido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/excel.
        /// </summary>
        internal static string CT_Excel {
            get {
                return ResourceManager.GetString("CT_Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.
        /// </summary>
        internal static string CT_ExcelX {
            get {
                return ResourceManager.GetString("CT_ExcelX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/gif.
        /// </summary>
        internal static string CT_Gif {
            get {
                return ResourceManager.GetString("CT_Gif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/x-icon.
        /// </summary>
        internal static string CT_Icon {
            get {
                return ResourceManager.GetString("CT_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/jpeg.
        /// </summary>
        internal static string CT_Jpg {
            get {
                return ResourceManager.GetString("CT_Jpg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/pdf.
        /// </summary>
        internal static string CT_Pdf {
            get {
                return ResourceManager.GetString("CT_Pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/png.
        /// </summary>
        internal static string CT_Png {
            get {
                return ResourceManager.GetString("CT_Png", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-rar-compressed.
        /// </summary>
        internal static string CT_Rar {
            get {
                return ResourceManager.GetString("CT_Rar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text/plain.
        /// </summary>
        internal static string CT_Text {
            get {
                return ResourceManager.GetString("CT_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/tiff.
        /// </summary>
        internal static string CT_Tif {
            get {
                return ResourceManager.GetString("CT_Tif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/msword.
        /// </summary>
        internal static string CT_Word {
            get {
                return ResourceManager.GetString("CT_Word", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.openxmlformats-officedocument.wordprocessingml.document.
        /// </summary>
        internal static string CT_WordX {
            get {
                return ResourceManager.GetString("CT_WordX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/zip.
        /// </summary>
        internal static string CT_Zip {
            get {
                return ResourceManager.GetString("CT_Zip", resourceCulture);
            }
        }
    }
}
