//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sismuni.Presentacion.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Iconos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Iconos() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sismuni.Presentacion.Web.Resources.Iconos", typeof(Iconos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon-siga16-doc-app.
        /// </summary>
        internal static string Icon16_Doc_Desconocido {
            get {
                return ResourceManager.GetString("Icon16_Doc_Desconocido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon-siga16-doc-excel.
        /// </summary>
        internal static string Icon16_Doc_Excel {
            get {
                return ResourceManager.GetString("Icon16_Doc_Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon-siga16-doc-img.
        /// </summary>
        internal static string Icon16_Doc_Imgs {
            get {
                return ResourceManager.GetString("Icon16_Doc_Imgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon-siga16-doc-pdf.
        /// </summary>
        internal static string Icon16_Doc_Pdf {
            get {
                return ResourceManager.GetString("Icon16_Doc_Pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon-siga16-doc-word.
        /// </summary>
        internal static string Icon16_Doc_Word {
            get {
                return ResourceManager.GetString("Icon16_Doc_Word", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon-siga16-doc-zip.
        /// </summary>
        internal static string Icon16_Doc_Zip {
            get {
                return ResourceManager.GetString("Icon16_Doc_Zip", resourceCulture);
            }
        }
    }
}
