//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sismuni.Presentacion.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mensajes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensajes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sismuni.Presentacion.Web.Resources.Mensajes", typeof(Mensajes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró información para los criterios ingresados.
        /// </summary>
        public static string Msj_NoSeEncontraronResultados {
            get {
                return ResourceManager.GetString("Msj_NoSeEncontraronResultados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha producido un error en el sistema, por favor comuníquese con el Administrador.
        /// </summary>
        public static string MsjeErrorSistema {
            get {
                return ResourceManager.GetString("MsjeErrorSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El expediente Nro : {0} fue modificado.
        /// </summary>
        public static string MsjeExpedienteModificado {
            get {
                return ResourceManager.GetString("MsjeExpedienteModificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El expediente Nro : {0} fue registrado.
        /// </summary>
        public static string MsjeExpedienteRegistrado {
            get {
                return ResourceManager.GetString("MsjeExpedienteRegistrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La solicitud Nro: {0} fue asignada.
        /// </summary>
        public static string MsjeInspeccionRegistrado {
            get {
                return ResourceManager.GetString("MsjeInspeccionRegistrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La solicitud Nro : {0} fue modificado.
        /// </summary>
        public static string MsjeSolicitudModificado {
            get {
                return ResourceManager.GetString("MsjeSolicitudModificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La solicitud Nro : {0} fue registrado.
        /// </summary>
        public static string MsjeSolicitudRegistrado {
            get {
                return ResourceManager.GetString("MsjeSolicitudRegistrado", resourceCulture);
            }
        }
    }
}
